### ISSUE TITLE
Inconsistent release dates

### ISSUE THREAD

**Issue by luismarques** [lowRISC/lowrisc-site#33]
In the page <https://www.lowrisc.org/docs/refresh-v0.6/>, the milestone "Oct 2018" links to <https://www.lowrisc.org/docs/refresh-v0.6/>, which says "Release version 0.6 (06-2018)"

**Comment by asb** [comment]
Fixed in https://github.com/lowRISC/lowrisc-site/commit/608a297de5e336ae6e69088b4e4da8429232369d

Thanks!
