### ISSUE TITLE
Homepage: job opportunities link gives SSL error

### ISSUE THREAD

**Issue by 9600** [lowRISC/lowrisc-site#37]
Looks to be just missing www prefix, but in any case perhaps the site should be configured to work equally on apex domain and www.

**Comment by asb** [comment]
I don't think GitHub pages has a workaround for this currently sadly :/ I'll fix the link, thanks

**Comment by asb** [comment]
Obviously we should move off GH pages at some point, but for now it's convenient...

**Comment by 9600** [comment]
Looks like it should, unless I'm missing something.

https://help.github.com/en/articles/setting-up-an-apex-domain-and-www-subdomain

Although would suggest we consider moving to Netlify. Hopefully we'd qualify for their Open Source Plan, but if not a Pro subscription is pretty good value.

https://www.netlify.com/legal/open-source-policy/

**Comment by asb** [comment]
I think the issue is still active. That page doesn't mention the certificate issue. See discussion here: https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116

Netlify looks like a good option if we don't want to self-host

**Comment by 9600** [comment]
Ah, shame, but easy fix for now anyway and we can consider our longer term options.
