### ISSUE TITLE
inittab link in untether-v0.2 tutorial is broken which leads to "Bad inittab entry at line" when kernel boots

### ISSUE THREAD

**Issue by cirosantilli** [lowRISC/lowrisc-site#9]

**Comment by wsong83** [comment]
It is because the original URL for inittab becomes unavailable from riscv/Berkeley.
I have the file copied locally and changed the script.
Let me know if it is still not working.

**Comment by cirosantilli** [comment]
@wsong83 awesome, kernel booted! Can't wait to see silicon benchmarks next year.
